packages:
  - 'apps/*'
  - 'packages/*'
  - 'internal/*'
catalogs:
  build:
    '@tailwindcss/vite': ^4.1.11
    '@vitejs/plugin-vue': ^6.0.0
    vite: ^7.0.5
    vite-plugin-inspect: ^11.3.0
  cli:
    pncat: ^0.2.6
  dev:
    '@vue/tsconfig': ^0.7.0
    typescript: ^5.8.3
    vue-tsc: ^3.0.3
  frontend:
    ant-design-vue: ~4.2.6
    echarts: ^5.6.0
    element-plus: ^2.10.2
    nprogress: ^0.2.0
    pinia: ^3.0.3
    vue: ^3.5.17
    vue-router: ^4.5.1
  icons:
    '@ant-design/icons-vue': ^7.0.1
  lint:
    eslint: ^9.31.0
    prettier: ^3.6.2
  monorepo:
    turbo: ^2.5.5
  network:
    axios: ^1.10.0
  prod:
    '@vue/shared': ^3.5.17
    js-cookie: ^3.0.5
    vant: ^4.9.21
  style:
    tailwindcss: ^4.1.11
  types:
    '@types/js-cookie': ^3.0.6
    '@types/node': ^24.0.15
    '@types/nprogress': ^0.2.3
